version: "2.1"
services:

  nifi:
    image: nifi
    build: nifi
    hostname: nifi
    ports:
      - "28080:8080"
    restart: always

  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: exit 0

  querydb_customers:
    build: customers/query_db/
    ports:
      - "27019:27017"
    restart: always

  commanddb_customers:
    build: customers/command_db/
    ports:
      - "5439:5432"
    healthcheck:
      test: exit 0
    restart: always

  rabbit:
    image: rabbit
    build: queue
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always


  querydb_orders:
    build: orders/query_db/
    ports:
      - "27020:27017"
    restart: always

  commanddb_orders:
    build: orders/command_db/
    ports:
      - "5440:5432"
    healthcheck:
      test: exit 0
    restart: always

  orders_service:
    build:
      context:
        orders
    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_HOST=commanddb_orders
      - DB_NAME=orders
      - PYTHONPATH=.
      - MONGO_HOST=querydb_orders
      - MONGO_PORT=27017
      - MONGO_DATABASE=orders
    depends_on:
      - querydb_orders
      - commanddb_orders
      - rabbit
    links:
      - querydb_orders
      - commanddb_orders
      - rabbit
    restart: always

  basket_service:
    build:
      context: basket
    depends_on:
      - rabbit
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    restart: always

  payment_service:
    build:
      context: payment
    depends_on:
      - rabbit
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
    restart: always

  customers_service:
    build:
      context:
        customers
    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_HOST=commanddb_customers
      - DB_NAME=customers
      - PYTHONPATH=.
      - MONGO_HOST=querydb_customers
      - MONGO_PORT=27017
      - MONGO_DATABASE=customers
    depends_on:
      - querydb_customers
      - commanddb_customers
      - rabbit
    links:
      - querydb_customers
      - commanddb_customers
      - rabbit
    restart: always

  querydb_warehouse:
    build: warehouse/query_db/
    ports:
      - "27021:27017"
    restart: always

  commanddb_warehouse:
    build: warehouse/command_db/
    ports:
      - "5441:5432"
    healthcheck:
      test: exit 0
    restart: always

  querydb_catalog:
    build: catalog/query_db/
    ports:
      - "27018:27017"
    restart: always

  commanddb_catalog:
    build: catalog/command_db/
    ports:
      - "5435:5432"
    healthcheck:
      test: exit 0
    restart: always

  catalog_service:
    build:
      context:
        catalog
    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_HOST=commanddb_catalog
      - DB_NAME=catalog
      - PYTHONPATH=.
      - MONGO_HOST=querydb_catalog
      - MONGO_PORT=27017
      - MONGO_DATABASE=catalog
    depends_on:
      - querydb_catalog
      - commanddb_catalog
      - rabbit
    links:
      - querydb_catalog
      - commanddb_catalog
      - rabbit
    restart: always

  warehouse_service:
    build:
      context:
        warehouse
    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_HOST=commanddb_warehouse
      - DB_NAME=warehouse
      - PYTHONPATH=.
      - MONGO_HOST=querydb_warehouse
      - MONGO_PORT=27017
      - MONGO_DATABASE=warehouse
    depends_on:
      - querydb_warehouse
      - commanddb_warehouse
      - rabbit
    links:
      - querydb_warehouse
      - commanddb_warehouse
      - rabbit
    restart: always

  orchestrator:
    build:
      context: orchestrator
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      PYTHONPATH: "."
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
      - customers_service
      - catalog_service
      - basket_service
    restart: always

  proxy:
    build:
      context: nginx
    ports:
      - "8080:80"
    depends_on:
      - orchestrator
    restart: always


volumes:
  redis-data: